### PR TITLE
Changed get_home_url  to get site_url

### PR DESCRIPTION
**Pull request by vimes1984**
This change is due to the links not working if the site is hosted in a subdirectory install as lots of worpress sites are...
I also mentioned this to you on twitter: https://twitter.com/vimes1984/status/598521721466036224
the fix I have is for the pro version but I'm assuming it's the same here... 
Also emailed you directly! 
Thanks for all the great plugins I use groups a lot and always send customers your way :D

### CODE REVIEW

**Comment by itthinx** [comment]
Hi thanks for your contribution, will be added to the new release! :)

**Comment by vimes1984** [comment]
no worries ! 
I use your plugins a lot they always save a ton of time :D 
Glad to have helped!

**Comment by itthinx** [comment]
That's great, always happy to hear that people find them useful, free and premium alike!

Hey, in case you're interested in joining ... http://www.itthinx.com/affiliate-area/

**Comment by vimes1984** [comment]
my problem with affiliates is that I feel I'm pushing a product for my own benfit, rather than it just being sodding good!

**Pull request merged**
